### ISSUE TITLE
1.18.2 can't right_click to do that

### ISSUE THREAD

**Issue by fengbinggan** [BakuPlayz/CropClick#83]

**Comment by fengbinggan** [comment]
![image](https://user-images.githubusercontent.com/105630073/217472478-2c4feeed-ef39-4401-a86c-a53424f40169.png)
can't use

**Comment by BakuPlayz** [comment]
Hello I'm sorry to hear your having issues.

What do you mean by you can't right click?

**Comment by BakuPlayz** [comment]
Do you get any errors in your console?

**Comment by fengbinggan** [comment]
![image](https://user-images.githubusercontent.com/105630073/218238567-8d4b08ec-47c5-4482-9a78-01d8ca3969d8.png)
![image](https://user-images.githubusercontent.com/105630073/218238575-0bba90f8-e006-48fb-8752-af47780f4208.png)
i can't right_click to get this.

**Comment by fengbinggan** [comment]
[12:23:29 WARN]: java.net.ConnectException: Connection timed out: connect
[12:23:29 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[12:23:29 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
[12:23:29 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
[12:23:29 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[12:23:29 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[12:23:29 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[12:23:29 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
[12:23:29 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[12:23:29 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[12:23:29 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[12:23:29 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[12:23:29 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[12:23:29 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[12:23:29 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[12:23:29 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[12:23:29 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[12:23:29 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[12:23:29 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[12:23:30 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[12:23:30 WARN]:        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
[12:23:30 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
[12:23:30 WARN]:        at CropClick-Latest (1).jar//com.github.bakuplayz.cropclick.http.HttpRequestBuilder.updateStatus(HttpRequestBuilder.java:187)
[12:23:30 WARN]:        at CropClick-Latest (1).jar//com.github.bakuplayz.cropclick.http.HttpRequestBuilder.doRequest(HttpRequestBuilder.java:176)
[12:23:30 WARN]:        at CropClick-Latest (1).jar//com.github.bakuplayz.cropclick.http.HttpRequestBuilder.post(HttpRequestBuilder.java:127)
[12:23:30 WARN]:        at CropClick-Latest (1).jar//com.github.bakuplayz.cropclick.update.UpdateManager.fetchUpdate(UpdateManager.java:127)
[12:23:30 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[12:23:30 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:23:30 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:23:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:23:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:23:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:23:30 INFO]: [CropClick] Update fetch failed! Make sure your online to keep CropClick up to date

these are all about the 'cropclick' plugin

**Comment by BakuPlayz** [comment]
> 

What other plugins do you have installed?

**Comment by fengbinggan** [comment]
![image](https://user-images.githubusercontent.com/105630073/218252821-d5f79ad9-5b68-482b-8217-47bd9e001fac.png)
![image](https://user-images.githubusercontent.com/105630073/218252828-63e48ae2-bbad-4f6f-80ee-9824ae7c4126.png)
when i remove all other plugins,i can't right_click to get the wheet also.

**Comment by fengbinggan** [comment]
[latest.log](https://github.com/BakuPlayz/CropClick/files/10713153/latest.log)

**Comment by BakuPlayz** [comment]
That's extremly weird. I've tried using the 2.0.1 version on 1.18.2 with paper spigot and cannot seem to reproduce this issue. I'll try once more to see if I can reproduce it.

**Comment by BakuPlayz** [comment]
Question, are you mayhaps standing in the spawn protected area? That might be the issue as to why you are unable to click the crop.

**Comment by fengbinggan** [comment]
i am op. have all permission

**Comment by fengbinggan** [comment]
![image](https://user-images.githubusercontent.com/105630073/218253362-eccdf8d2-0151-4318-b242-4d598f71ac3c.png)

**Comment by BakuPlayz** [comment]
Hummm well then that should not cause issues then, how does your toggle look? Does it say Status: Enabled when you hold over your head?

**Comment by fengbinggan** [comment]
emm,how to hold over my head

**Comment by BakuPlayz** [comment]
![bild](https://user-images.githubusercontent.com/32036218/218253773-08140bc5-42b7-4686-9fb0-05b97f71df13.png)
Then when pressed it should show this:
![bild](https://user-images.githubusercontent.com/32036218/218253787-3cbecc77-4d37-4070-b17e-444f6734dbf3.png)

**Comment by fengbinggan** [comment]
![image](https://user-images.githubusercontent.com/105630073/218254005-b54f0c01-5bf7-4df2-b6cd-b45605937181.png)

**Comment by BakuPlayz** [comment]
I'm sorry for not noticing this till now, the image you sent before about the world being "Banished:  true", click that once so it says "Banished: false", then it should all work :)

**Comment by fengbinggan** [comment]
![image](https://user-images.githubusercontent.com/105630073/218254255-8ef937ad-23d5-40df-b37a-b64216e7ab3c.png)
It didn't work also

**Comment by BakuPlayz** [comment]
![bild](https://user-images.githubusercontent.com/32036218/218254404-17c495fc-7d76-4023-9b24-629e2ee30a4a.png)
And is player interaction also allowed?

**Comment by fengbinggan** [comment]
![image](https://user-images.githubusercontent.com/105630073/218254468-44dc1d08-708b-479c-a0fc-0e20fe2382ba.png)
![image](https://user-images.githubusercontent.com/105630073/218254481-1d65ec46-d039-459a-aed4-8a8684771210.png)
![image](https://user-images.githubusercontent.com/105630073/218254488-57db77a6-ee87-4e4f-a9a9-e319d2bfcfd9.png)
![image](https://user-images.githubusercontent.com/105630073/218254492-d381a6cc-47ee-4700-b82b-fa507152d958.png)
these are my settings and It didn't work.

**Comment by BakuPlayz** [comment]
![bild](https://user-images.githubusercontent.com/32036218/218254595-d95e8107-175d-4ae8-8c89-168daf829b4e.png)
what does it say when you hover the wheat 
![bild](https://user-images.githubusercontent.com/32036218/218254611-0be6ad47-16a5-4e63-a723-b2f545da4f3b.png)

**Comment by fengbinggan** [comment]
![image](https://user-images.githubusercontent.com/105630073/218254846-c4cb536b-17d9-456f-ae95-c59c03f2949c.png)

**Comment by BakuPlayz** [comment]
Then that's not a problem neither. Humm does other crops work?

**Comment by fengbinggan** [comment]
no

**Comment by fengbinggan** [comment]
emm，i have a server,can you join and help me?

**Comment by BakuPlayz** [comment]
Sure thing :)

**Comment by fengbinggan** [comment]
mc.tiangmo.cn

**Comment by BakuPlayz** [comment]
Cannot seem to join, it keeps timing me out.

**Comment by fengbinggan** [comment]
mc.tiangmo.cf
how about this

**Comment by BakuPlayz** [comment]
Nope still able to join.

**Comment by fengbinggan** [comment]
emm where are you

**Comment by BakuPlayz** [comment]
Sweden

**Comment by fengbinggan** [comment]
![image](https://user-images.githubusercontent.com/105630073/218256261-3678e69e-708a-4456-8c2d-5c106bb83e33.png)
do you have vpn?

**Comment by fengbinggan** [comment]
emm,Did you just sign up?

**Comment by fengbinggan** [comment]
[19:52:01 WARN]: [CropClick] Plugin CropClick v2.0.1 generated an exception while executing task 3191530
java.lang.IllegalStateException: New flags cannot be registered at this time
        at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.register(SimpleFlagRegistry.java:60) ~[worldguard-bukkit-7.0.7-dist.jar:?]
        at com.github.bakuplayz.cropclick.addons.addon.WorldGuardAddon.registerFlag(WorldGuardAddon.java:64) ~[CropClick-Latest (1).jar:?]
        at com.github.bakuplayz.cropclick.addons.addon.WorldGuardAddon.<init>(WorldGuardAddon.java:56) ~[CropClick-Latest (1).jar:?]
        at com.github.bakuplayz.cropclick.addons.AddonManager.registerAddons(AddonManager.java:96) ~[CropClick-Latest (1).jar:?]
        at com.github.bakuplayz.cropclick.addons.AddonManager.<init>(AddonManager.java:67) ~[CropClick-Latest (1).jar:?]
        at com.github.bakuplayz.cropclick.CropClick.registerManagers(CropClick.java:316) ~[CropClick-Latest (1).jar:?]
        at com.github.bakuplayz.cropclick.CropClick.lambda$onReset$0(CropClick.java:187) ~[CropClick-Latest (1).jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-388]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-388]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
_______________________________________________________________________________________________________
when i /crop reset
The above will appear.
Is there a problem with this.

**Comment by BakuPlayz** [comment]
Still cannot seem to join with a VPN. Also that other issue should not even appear upon performing that command.. especially not with only CropClick installed.

**Comment by fengbinggan** [comment]
http://14.29.161.131:8828/down/K8TXODhTndJU.zip
I use this paper.

**Comment by fengbinggan** [comment]
oh my gad,it's amazing!
I can right_click to get crop!

**Comment by fengbinggan** [comment]
I think it has something to do with server restarts.

**Comment by fengbinggan** [comment]
Sorry for delaying you for so long.

**Comment by BakuPlayz** [comment]
That's amazing! I'm happy to hear that your issue was solved :D
